### ISSUE TITLE
Slack? Facebook?

### ISSUE THREAD

**Issue by spasarok** [DevOpsDSM/devopsdsm#27]
Does this group have a Slack channel or Facebook page (or any other way of promoting member interaction)?

**Comment by sherzberg** [comment]
Related: https://github.com/DevOpsDSM/devopsdsm/issues/13

Anyone else have a vote?

What would you like to use it for? General discussion? Questions?

**Comment by adamdecaf** [comment]
Chat would be nice. Probably easier to distribute links from talks and projects. 

As for a platform, anything with an irc gateway works :P

**Comment by spasarok** [comment]
I think it'd be good for general discussions, questions, networking, talk about new products, etc. For example, I have some follow-up questions from the presentation last week but no one to ask.

**Comment by darrinholst** [comment]
I've always thought it would be nice to have a Des Moines focused slack with different channels for the various groups (unless it already exists and nobody invited me 😿 ). I know at least Nashville does this with http://nashdev.com/ (using [slackin](https://github.com/rauchg/slackin) for the registration process). 

It's a free idea anyway `¯\_(ツ)_/¯`

**Comment by dustyjuhl** [comment]
It'd be nice to see Des Moines with a centralized tech hub (as I've seen
elsewhere, e.g. Techlahoma <http://www.techlahoma.org/>). I've seen
multiple previous efforts fail. I listed 18 separate user group events on
the DAQAA <http://www.daqaa.com> events calendar for the month of March,
and have probably missed some. There's 20+ groups locally (I have a Google
Doc I can share), some with individual websites, some on Meetup, etc.

For now, this is what I've seen.

http://dsmwebcollective.com/

http://dsmwebcollective.herokuapp.com/

The dsmwebcollective Slack team doesn't have a channel for each group, but
does list events. Most of the individual groups have their own Slack team
(if they're on Slack at all):

- DAQAA <http://www.daqaa.com> (I don't currently have an easy sign-up for
the general public...yet)
- experiencing UX <https://www.meetup.com/experiencing-UX-DSM/>
- IADNUG <http://www.iadnug.org>
- Pyowa <http://www.pyowa.org/>

Dusty


Dusty Juhl, Vice President/Treasurer
Des Moines Area Quality Assurance Association
communications.daqaa@gmail.com


Visit our website <http://www.daqaa.com/>

Like us on Facebook
<http://www.facebook.com/DesMoinesAreaQualityAssuranceAssociation>

Follow us on Twitter <http://twitter.com/DAQAA_com>

<http://www.linkedin.com/groups?gid=2105809>

Join our Google Group <https://groups.google.com/forum/?hl=en#!forum/daqaa>
Join our LinkedIn <http://www.linkedin.com/groups?gid=2105809> group
Subscribe to our e-mail list
<http://daqaa.us3.list-manage1.com/subscribe?u=d4838f1cac786aa8dbc83d58b&id=4078de1719>

**Comment by dustyjuhl** [comment]
I'm sure I need to update this list (there's a lot of Meetup groups I don't have covered), but here's a link to the existing list of User Groups I have in the local community.

https://docs.google.com/spreadsheets/d/1de1Wct0DXS72C3I7WoZ6RC6iR73mZiYYaCDXhMnz3qM/edit?usp=sharing

**Comment by zach-taylor** [comment]
@dustyjuhl @darrinholst a shared Slack org sounds like a great idea to me. @iowaruby has been thinking about creating a Slack for their members. I regularly attend multiple groups, so it would be nice not to have to join (and manage credentials for) half a dozen different Slack orgs.

**Comment by spasarok** [comment]
Sweet, I'm going to try to start using the DSM Web Collective Slack channel (http://dsmwebcollective.herokuapp.com/). It looks kind of dead right now, but maybe we can revive it... or get the devops channel going, at least.

**Comment by adamdecaf** [comment]
Could we enable the irc gateway?

**Comment by darrinholst** [comment]
I started using gitter today for a couple other github projects and it seems pretty good so far. I think this is a recent change, but communities/rooms/channels no longer have to be tied to a github project so I created [central-iowa](https://gitter.im/central-iowa/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) which I guess is just the lobby? I also created the [central-iowa/devops](https://gitter.im/central-iowa/devops?utm_source=share-link&utm_medium=link&utm_campaign=share-link) room underneath it to try out the room per topic/group idea. If it sprouts any legs I can add admins and/or more rooms. 

I'm not sure why more people aren't using it tbh. Maybe it's just one more chat service that people don't want. I like that anyone can join instead of setting up a separate app to manage slack invites. I also like the fact that you can use your existing github account to login.

It's out there anyway. I'll throw it out on twitter to see if there's any traction. irc integration looks to be available [here](https://irc.gitter.im/).

**Comment by sherzberg** [comment]
Awesome! Thanks! I like that there is no invite required. I'll be sure and mention this at the next meeting.
